export const REQUEST_CREDITS = 'REQUEST_CREDITS'; //请求学分数据
export const REQUEST_INSURANCE_LIABILITY = 'REQUEST_INSURANCE_LIABILITY'; //请求保险总保额和保险弹框
export const REQUEST_STUDY_CONTENT = 'REQUEST_STUDY_CONTENT'; //请求学习内容
export const REQUEST_TASK_LIST = 'REQUEST_TASK_LIST'; //请求任务列表的数据
export const REQUEST_STATUS_SUBSCRIBE = 'REQUEST_STATUS_SUBSCRIBE'; //查询预约状态描述
export const REQUEST_PREPARE_STATUS = 'REQUEST_PREPARE_STATUS'; //请求预约状态
export const REQUEST_CANCEL_PREPARE_STATUS = 'REQUEST_CANCEL_PREPARE_STATUS'; //请求取消预约状态
export const REQUEST_GET_CREDITS = 'REQUEST_GET_CREDITS'; //请求获取学分
export const REQUEST_SHARE_CREDITS = 'REQUEST_SHARE_CREDITS'; //请求分享学分
export const REQUEST_RISK = 'REQUEST_RISK'; //请求风控的接口
export const REQUEST_HUEMONITORHOME = 'REQUEST_HUEMONITORHOME'; // 量化监控上报
export const REQUEST_UPLOAD = 'REQUEST_UPLOAD'; // 图片上传

export const RECEIVE_CREDITS = 'RECEIVE_CREDITS'; //接收学分数据
export const RECEIVE_INSURANCE_LIABILITY = 'RECEIVE_INSURANCE_LIABILITY'; //接收保险总保额和保险弹框
export const RECEIVE_STUDY_CONTENT = 'RECEIVE_STUDY_CONTENT'; //接收学习内容
export const RECEIVE_TASK_LIST = 'RECEIVE_TASK_LIST'; //接收任务列表的数据
export const RECEIVE_PREPARE_STATUS = 'RECEIVE_PREPARE_STATUS'; //接收预约状态
export const RECEIVE_STATUS_SUBSCRIBE = 'RECEIVE_STATUS_SUBSCRIBE'; //接收预约状态描述
export const RECEIVE_GET_CREDITS = 'RECEIVE_GET_CREDITS'; //接收获取学分

export const RECEIVE_ENSURE_MODAL_SHOW = 'RECEIVE_ENSURE_MODAL_SHOW'; //责任弹框的显隐
export const RECEIVE_TASK_MODAL = 'RECEIVE_TASK_MODAL'; //领取任务奖励弹框显隐
export const RECEIVE_MODAL_SHOW = 'RECEIVE_MODAL_SHOW'; //接收弹框的显隐
export const RECEIVE_SAVE_WEEK = 'RECEIVE_SAVE_WEEK'; //接受具体星期的展示
export const RECEIVE_UPLOAD = 'RECEIVE_UPLOAD'; //接受上传的图片
export const RECEIVE_CANVASSTR = 'RECEIVE_CANVASSTR'; //保存canvas绘制的图
export const RECEIVE_CANVAS_MODAL = 'RECEIVE_CANVAS_MODAL'; //保存canvas绘制邀请弹框
